config/routes.rb
GoogleApiSample::Application.routes.draw do
  get "home/index"

  get "campaign/index"

  get "account/index"
  get "account/input"
  get "account/select"

  get "login/prompt"
  get "login/callback"
  get "login/logout"

  get "report/index"
  post "report/get"

  root :to => "home#index"
end

app/models/campaign.rb
class Campaign
  attr_reader :id
  attr_reader :name
  attr_reader :status

  def initialize(api_campaign)
    @id = api_campaign[:id]
    @name = api_campaign[:name]
    @status = api_campaign[:status]
  end

  def self.get_campaigns_list(response)
    result = {}
    if response[:entries]
      response[:entries].each do |api_campaign|
        campaign = Campaign.new(api_campaign)
        result[campaign.id] = campaign
      end
    end
    return result
  end
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController

  PAGE_SIZE = 50

  def index()
    @selected_account = selected_account

    if @selected_account
      response = request_campaigns_list()
      if response
        @campaigns = Campaign.get_campaigns_list(response)
        @campaign_count = response[:total_num_entries]
      end
    end
  end

  private

  def request_campaigns_list()
    api = get_adwords_api()
    service = api.service(:CampaignService, get_api_version())
    selector = {
      :fields => ['Id', 'Name', 'Status'],
      :ordering => [{:field => 'Id', :sort_order => 'ASCENDING'}],
      :paging => {:start_index => 0, :number_results => PAGE_SIZE}
    }
    result = nil
    begin
      result = service.get(selector)
    rescue AdwordsApi::Errors::ApiException => e
      logger.fatal("Exception occurred: %s\n%s" % [e.to_s, e.message])
      flash.now[:alert] =
          'API request failed with an error, see logs for details'
    end
    return result
  end
end

app/views/campaign/index.html.erb
<h1>Campaigns list</h1>

<% if @selected_account.nil? %>
  <div class="notice">No account selected!</div>

<% else %>

  <% if @campaigns.nil? or @campaigns.empty? %>
    <ul><li>No campaigns available.</ul>
  <% else %>
    <ul><li>Total number of campaigns: <%= @campaign_count %></ul>
    <table>
      <tr>
        <th>ID
        <th>Name
        <th>Status
    <% @campaigns.each do |id, campaign| %>
      <tr>
        <td><%= campaign.id %>
        <td><%= campaign.name %>
        <td><%= campaign.status %>
    <% end %>
    </table>
  <% end %>

<% end %>

<div id="local-footer">
  <span class="small-print"><%= link_to("Back to home", home_index_path) %></span>
</div>